MasterFinalProject/MasterFinalProjectAdmin/Models/TeacherSubject.cs
using System.ComponentModel.DataAnnotations;

namespace MasterFinalProjectAdmin.Models
{
    public class TeacherSubject
    {
        [Key]
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public Subject Subject { get; set; }
        public int TeacherId { get; set; }
        public Teacher Teacher { get; set; }
    }
}

MasterFinalProject/MasterFinalProjectAdmin/ViewModels/TeacherSubjectViewModel.cs
using MasterFinalProjectAdmin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MasterFinalProjectAdmin.ViewModels
{
    public class TeacherSubjectViewModel
    {
        public IEnumerable<Subject> AllSubjects { get; set; }
        public IEnumerable<Teacher> AllTeachers { get; set; }
        public int TeacherId { get; set; }
        public int SubjectId { get; set; }

        public IEnumerable<SelectListItem> GetSubjectsSelectList(IEnumerable<Subject> subjects)
        {
            return subjects.Select((e) => new SelectListItem
                {
                    Text = e.Name.ToString(),
                    Value = e.Id.ToString(),
                    Selected= true
                });
        }
        public IEnumerable<SelectListItem> GetTeachersSelectList(IEnumerable<Teacher> teachers)
        {
            return teachers.Select((e) => new SelectListItem
            {
                Text = e.Name.ToString(),
                Value = e.Id.ToString(),
                Selected = true
            });
        }

    }
}

MasterFinalProject/MasterFinalProjectAdmin/Controllers/TeacherSubjectController.cs
using MasterFinalProjectAdmin.Interface;
using MasterFinalProjectAdmin.Models;
using MasterFinalProjectAdmin.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MasterFinalProjectAdmin.Controllers
{
    [Route("[controller]")]
    public class TeacherSubjectController : Controller
    {
        private readonly ITeacherSubjecRepository repository;
        public TeacherSubjectController(ITeacherSubjecRepository repository)
        {
            this.repository = repository;
        }
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> Index()
        {
            return View(await repository.GetAll());
        }
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> Create()
        {
            var model = new TeacherSubjectViewModel()
            {
                AllSubjects = await repository.GetAllSubject(),
                AllTeachers = await repository.GetAllTeacher()
            };
            
            return View(model);
        }
        [HttpPost]
        [Route("[action]")]

        public async Task<IActionResult> Create(int teacherId,int subjectId)
        {
            
            await repository.Create(teacherId, subjectId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Route("[action]")]
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Teachers = new SelectList(await repository.GetAllTeacher(), "Id", "Name");
            ViewBag.Subjects = new SelectList(await repository.GetAllSubject(), "Id", "Name");

            var clas = await repository.GetById(id);

            return View(clas);
        }
        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> Update(int id, TeacherSubject className)
        {
            if (await repository.Update(id, className) != null)
            {
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        [Route("[action]/{id}")]
        public async Task<IActionResult> DeleteC(int id)
        {
            if (await repository.GetById(id) != null)
            {
                await repository.Delete(id);
                return RedirectToAction("Index");
            }
            return NotFound();

        }
    }
}

MasterFinalProject/MasterFinalProjectAdmin/Views/TeacherSubject/Create.cshtml
@using MasterFinalProjectAdmin.ViewModels;
@model TeacherSubjectViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Yarat</h2>

<h4>Müəllim-Fənn</h4>
<hr />
<div class="row">
    <div class="form-group col-12">
        <form asp-action="Create" method="post" enctype="multipart/form-data" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-row">

                <div class="col-4 mb-3">
                    <label asp-for="TeacherId" class="control-label">Muellim</label>

                    @Html.DropDownListFor(model => model.TeacherId,
                    Model.GetTeachersSelectList(Model.AllTeachers),
                    new { @class ="form-control" })
                </div>
                <div class="col-4 mb-3">
                    <label asp-for="SubjectId" class="control-label">Fenn</label>

                    @Html.DropDownListFor(model => model.SubjectId,
                    Model.GetSubjectsSelectList(Model.AllSubjects),
                    new { @class ="form-control" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Yarat" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Siayhıya Qayıt</a>
</div>

MasterFinalProject/MasterFinalProjectAdmin/Views/TeacherSubject/Index.cshtml
@using MasterFinalProjectAdmin.Helpers;
@model List<TeacherSubject>
@{
    ViewData["Title"] = "Class";
}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Müəllim-Fənn</h4>
                <a asp-action="Create" class="btn btn-success mt-3">Yeni Muellim Fenn Yarat</a>

                <div class="table-responsive pt-3">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Müəllim
                                </th>
                                  <th>
                                    Fənn
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (TeacherSubject item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Teacher.Name
                                    </td>
                                     <td>
                                        @item.Subject.Name
                                    </td>
                                    <td>                                      
                                        <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning">
                                            Yenilə
                                            <i class="mdi mdi-table-edit"></i>
                                        </a>
                                        <a asp-action="DeleteC" asp-controller="TeacherSubject" asp-route-id="@item.Id" class="btn btn-danger">
                                            Sil
                                            <i class="mdi mdi-delete"></i>
                                        </a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

MasterFinalProject/MasterFinalProjectAdmin/Views/TeacherSubject/Update.cshtml
@model TeacherSubject
@{
    ViewData["Title"] = "update";
}

<h2>Yenilə</h2>

<h4>Müəllim-Fənn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="col-4 mb-3">
                <label asp-for="Teacher" class="control-label">Müəllim</label>
                @Html.DropDownList("TeacherId", (IEnumerable<SelectListItem>)ViewBag.Teachers, null, new { @class ="form-control" })
            </div>
            <div class="col-4 mb-3">
                <label asp-for="SubjectId" class="control-label">Fənn</label>
                @Html.DropDownList("SubjectId", (IEnumerable<SelectListItem>)ViewBag.Subjects, null, new { @class ="form-control" })
            </div>
            <div class="form-group">
                <input type="submit" value="Yenilə" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Geri Qayıt</a>
</div>